name: sduoj-judger-local

services:
  sduoj-judger:
    image: sduoj-judger:local
    environment:
      - RABBITMQ_HOST=test.sduoj.com
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
      - SUBMIT_SERVICE_URL=test.sduoj.com:19014
      - PROBLEM_SERVICE_URL=test.sduoj.com:19013
      - FILESYS_SERVICE_URL=test.sduoj.com:19012

